version: "3.8"

services:
  web:
    build: .
    container_name: web
    command:
      - /bin/bash
      - -c
      - |
        python web/manage.py makemigrations
        python web/manage.py migrate
        python web/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - webdb
  api:
    build: .
    container_name: api
    command:
      - /bin/bash
      - -c
      - |
        python api/manage.py makemigrations
        python api/manage.py migrate
        python api/manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/usr/src/app
    ports:
      - "8001:8001"
    depends_on:
      - apidb
  webdb:
    image: postgres
    container_name: webdb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - webdbdata:/var/lib/postgresql/data
  apidb:
    image: postgres
    container_name: apidb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - apidbdata:/var/lib/postgresql/data
volumes:
  webdbdata:
  apidbdata:
