# Generated by Django 3.2.8 on 2021-10-30 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('front', '0003_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='front_key_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
