# Generated by Django 3.2.8 on 2021-10-31 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_key_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='token',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
